@BaseURL = http://localhost:5171

### Get all warehouses
GET {{BaseURL}}/api/Warehouse
Accept: application/json

### Get a warehouse by Id
GET {{BaseURL}}/api/Warehouse/1
Accept: application/json

### Add a new warehouse
POST {{BaseURL}}/api/Warehouse
Content-Type: application/json

{
  "warehouseCode": "W101",
  "location": "Prague"
}

### Update a warehouse by Id
PUT {{BaseURL}}/api/Warehouse/1
Content-Type: application/json

{
  "warehouseCode": "W101",
  "location": "Pardubice"
}

### Delete a warehouse by Id
DELETE {{BaseURL}}/api/Warehouse/4

//////////////////////////////////////////////

### Get all airplanes
GET {{BaseURL}}/api/Airplane
Accept: application/json

### Get an airplane by Id
GET {{BaseURL}}/api/Airplane/1
Accept: application/json

### Add a new airplane
POST {{BaseURL}}/api/Airplane
Content-Type: application/json

{
  "airplaneCode": "A109",
  "maxLoad": 5000.00,
  "warehouseId": 1
}

### Update an airplane by Id
PUT {{BaseURL}}/api/Airplane/1
Content-Type: application/json

{
  "airplaneCode": "A101",
  "maxLoad": 6000.00,
  "currentLoad": 2000.00,
  "warehouseId": 2
}

### Delete an airplane by Id
DELETE {{BaseURL}}/api/Airplane/4

//////////////////////////////////////////////

### Get all cargos
GET {{BaseURL}}/api/Cargo
Accept: application/json

### Get a cargo by Id
GET {{BaseURL}}/api/Cargo/1
Accept: application/json

### Add a new cargo
POST {{BaseURL}}/api/Cargo
Content-Type: application/json

{
  "cargoCode": "C122",
  "description": "Books",
  "weight": 300,
  "status": 0,
  "isInWarehouse": true,
  "isInAirplane": false,
  "warehouseId": 1
}

### Update a cargo by Id
PUT {{BaseURL}}/api/Cargo/1
Content-Type: application/json

{
  "cargoCode": "C666",
  "description": "Books",
  "weight": 300,
  "status": 0,
  "isInWarehouse": true,
  "isInAirplane": false,
  "warehouseId": 1
}

### Delete a cargo by Id
DELETE {{BaseURL}}/api/Cargo/23
